---
services:
  kimai_web:
    image: lscr.io/linuxserver/kimai:${KIMAI_VERSION}
    container_name: kimai-web
    restart: unless-stopped
    depends_on:
      kimai_db:
        condition: service_started
        required: true
        restart: true
    secrets:
      - connection_string
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      FILE__DATABASE_URL: /run/secrets/connection_string
    hostname: kimai-web
    networks:
      kimai_network: null
    ports:
      - name: web (http)
        target: 80
        published: ${HTTP_PORT}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
      - name: web (https)
        target: 443
        published: ${HTTPS_PORT}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: https
        mode: host
    volumes:
      - type: volume
        source: kimai_web_config
        target: /config
        read_only: false
        volume:
          nocopy: false

  kimai_db:
    image: lscr.io/linuxserver/mariadb:${MARIADB_VERSION}
    container_name: kimai-db
    restart: unless-stopped
    secrets:
      - root_password
      - user_password
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      FILE__MYSQL_ROOT_PASSWORD: /run/secrets/root_password
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      FILE__MYSQL_PASSWORD: /run/secrets/user_password
    expose:
      - ${MYSQL_PORT}
    hostname: kimai-db
    networks:
      kimai_network: null
    volumes:
      - type: volume
        source: kimai_db_config
        target: /config
        read_only: false
        volume:
          nocopy: false

networks:
  kimai_network:
    name: kimai-network
    driver: bridge
    external: false
    internal: false
    enable_ipv4: true
    enable_ipv6: false

secrets:
  connection_string:
    file: connection_string.secret
  root_password:
    file: root_password.secret
  user_password:
    file: user_password.secret

volumes:
  kimai_web_config:
    name: kimai-web-config
    external: false
  kimai_db_config:
    name: kimai-db-config
    external: false
