---
name: kavita

services:
  kavita:
    image: lscr.io/linuxserver/kavita${TAG:+:}${TAG}${DIGEST:+@}${DIGEST}
    container_name: kavita
    restart: unless-stopped
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
    hostname: kavita
    networks:
      network: null
    ports:
      - name: web ui
        target: 5000
        published: ${WEB_UI_PORT:-5000}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: volume
        source: config
        target: /config
        read_only: false
      - type: volume
        source: comics
        target: /data/comics
        read_only: true
      - type: volume
        source: manga
        target: /data/manga
        read_only: true

networks:
  network:
    name: kavita-network
    driver: bridge
    external: false
    internal: false
    attachable: false

volumes:
  config:
    name: kavita-configuration
    external: false
    labels:
      stacks.kavita.volumes.config.description: kavita configuration
  comics:
    name: kavita-comics
    external: false
    labels:
      stacks.kavita.volumes.comics.description: kavita comics
    driver_opts:
      type: cifs
      device: "${DEVICE?error}/Books/Comics"
      o: "vers=3.0,username=${USERNAME?error},password=${PASSWORD?error},uid=${PUID:-1000},gid=${PGID:-1000},ro"
  manga:
    name: kavita-manga
    external: false
    labels:
      stacks.kavita.volumes.manga.description: kavita manga
    driver_opts:
      type: cifs
      device: "${DEVICE?error}/Books/Manga"
      o: "vers=3.0,username=${USERNAME?error},password=${PASSWORD?error},uid=${PUID:-1000},gid=${PGID:-1000},ro"
...
