name: immich

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_SERVER_VERSION:-release}
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
        required: true
        restart: true
      database:
        condition: service_healthy
        required: true
        restart: true
    healthcheck:
      disable: false
    secrets:
      - database-password
    environment:
      TZ: ${TZ:-Etc/UTC}
      DB_HOSTNAME: ${DB_HOSTNAME:-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME:-immich}
      DB_PASSWORD_FILE: /run/secrets/database-password
    hostname: immich-server
    networks:
      immich-network: null
    ports:
      - name: web (http)
        target: 2283
        published: ${HTTP_PORT:-2283}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: ${UPLOAD_LOCATION}
        target: /usr/src/app/upload
        read_only: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_MACHINE_LEARNING_VERSION:-release}
    restart: unless-stopped
    healthcheck:
      disable: false
    hostname: immich-machine-learning
    networks:
      immich-network: null
    volumes:
      - type: volume
        source: model-cache
        target: /cache
        read_only: false

  redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    hostname: immich-redis
    networks:
      immich-network: null

  database:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    restart: unless-stopped
    secrets:
      - database-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/database-password
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: --data-checksums
      DB_STORAGE_TYPE: HDD
    expose:
      - ${DB_PORT:-5432}
    hostname: immich-postgres
    networks:
      immich-network: null
    volumes:
      - type: bind
        source: ${DB_DATA_LOCATION}
        target: /var/lib/postgresql/data
        read_only: false

networks:
  immich-network:
    name: immich-network
    driver: bridge
    external: false
    internal: false
    enable_ipv4: true
    enable_ipv6: false

secrets:
  database-password:
    file: database_password.secret

volumes:
  model-cache:
    name: model-cache
    external: false
