---
name: caddy

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    environment:
      DUCKDNS_DOMAIN: ${DUCKDNS_DOMAIN?error}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN?error}
    hostname: caddy
    networks:
      network: null
      reverse-proxy: null
    ports:
      - name: web ui (http, tcp)
        target: 80
        published: ${WEB_UI_HTTP_PORT:-80}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
      - name: web ui (http, udp)
        target: 80
        published: ${WEB_UI_HTTP_PORT:-80}
        host_ip: 0.0.0.0
        protocol: udp
        app_protocol: http
        mode: host
      - name: web ui (https, tcp)
        target: 443
        published: ${WEB_UI_HTTPS_PORT:-443}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
      - name: web ui (https, udp)
        target: 443
        published: ${WEB_UI_HTTPS_PORT:-443}
        host_ip: 0.0.0.0
        protocol: udp
        app_protocol: http
        mode: host
    volumes:
      - type: volume
        source: config
        target: /config
        read_only: false
      - type: volume
        source: data
        target: /data
        read_only: false

networks:
  network:
    name: caddy-network
    driver: bridge
    attachable: false
    external: false
    internal: false
  reverse-proxy:
    external: true

volumes:
  config:
    name: caddy-config
    external: false
  data:
    name: caddy-data
    external: false
