---
name: caddy

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    environment:
      DUCKDNS_DOMAIN: ${DUCKDNS_DOMAIN}
      DUCKDNS_RESOLVER: ${DUCKDNS_RESOLVER}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
    hostname: caddy
    networks:
      caddy-network: null
    ports:
      - name: web ui (http, tcp)
        target: 80
        published: ${WEB_UI_HTTP_PORT:-80}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
      - name: web ui (http, udp)
        target: 80
        published: ${WEB_UI_HTTP_PORT:-80}
        host_ip: 0.0.0.0
        protocol: udp
        app_protocol: http
        mode: host
      - name: web ui (https, tcp)
        target: 443
        published: ${WEB_UI_HTTPS_PORT:-443}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
      - name: web ui (https, udp)
        target: 443
        published: ${WEB_UI_HTTPS_PORT:-443}
        host_ip: 0.0.0.0
        protocol: udp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: volume
        source: caddy-config
        target: /config
        read_only: false
      - type: volume
        source: caddy-data
        target: /data
        read_only: false

networks:
  caddy-network:
    driver: bridge
    external: false
    internal: false
    enable_ipv4: true
    enable_ipv6: false

volumes:
  caddy-config:
    name: caddy-config
    external: false
  caddy-data:
    name: caddy-data
    external: false
