---
name: heimdall

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:${VERSION:-latest}
    container_name: heimdall
    restart: unless-stopped
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
    hostname: heimdall
    networks:
      heimdall-network: null
    ports:
      - name: web (http)
        target: 80
        published: ${HTTP_PORT:-80}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
      - name: web (https)
        target: 443
        published: ${HTTPS_PORT:-443}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: https
        mode: host
    volumes:
      - type: volume
        source: heimdall-config
        target: /config
        read_only: false

networks:
  heimdall-network:
    name: heimdall-network
    driver: bridge
    external: false
    internal: false
    enable_ipv4: true
    enable_ipv6: false

volumes:
  heimdall-config:
    name: heimdall-config
    external: false
