---
name: monitoring

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:-latest}
    container_name: monitoring-cadvisor
    restart: unless-stopped
    depends_on:
      loki:
        condition: service_started
        restart: true
    privileged: true
    command:
      - --docker_only=true
    devices:
      - /dev/kmsg
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    hostname: monitoring-cadvisor
    networks:
      monitoring-network: null
    ports:
      - name: cAdvisor web (http)
        target: 8080
        published: ${CADVISOR_HTTP_PORT:-8080}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /dev/disk
        target: /dev/disk
        read_only: true
      - type: bind
        source: /etc/machine-id
        target: /etc/machine-id
        read_only: true

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-latest}
    container_name: monitoring-node-exporter
    restart: unless-stopped
    depends_on:
      loki:
        condition: service_started
        restart: true
    command:
      - --path.rootfs=/host
    pid: host
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    hostname: monitoring-node-exporter
    networks:
      monitoring-network: null
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
        bind:
          propagation: rslave

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: monitoring-prometheus
    restart: unless-stopped
    depends_on:
      cadvisor:
        condition: service_healthy
        restart: true
      node-exporter:
        condition: service_started
        restart: true
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    hostname: monitoring-prometheus
    networks:
      monitoring-network: null
    ports:
      - name: prometheus web (http)
        target: 9090
        published: ${PROMETHEUS_HTTP_PORT:-9090}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: ./prometheus.yaml
        target: /etc/prometheus/prometheus.yml
        read_only: false
      - type: volume
        source: monitoring-prometheus-data
        target: /prometheus
        read_only: false

  loki:
    image: grafana/loki:${LOKI_VERSION:-latest}
    container_name: monitoring-loki
    restart: unless-stopped
    command:
      - -config.file=/etc/loki/loki-config.yaml
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    hostname: monitoring-loki
    networks:
      monitoring-network: null
    ports:
      - name: loki web (http)
        target: 3100
        published: ${LOKI_HTTP_PORT:-3100}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: ./loki.yaml
        target: /etc/loki/loki-config.yaml
        read_only: false
      - type: volume
        source: monitoring-loki-data
        target: /data/loki
        read_only: false

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: monitoring-grafana
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
        restart: true
      loki:
        condition: service_started
        restart: true
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_SIGNOUT_MENU: true
      GF_AUTH_DISABLE_LOGIN_FORM: true
    hostname: monitoring-grafana
    networks:
      monitoring-network: null
    ports:
      - name: grafana web (http)
        target: 3000
        published: ${GRAFANA_HTTP_PORT:-9100}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: ./grafana/datasources.yaml
        target: /etc/grafana/provisioning/datasources/datasource.yaml
        read_only: false
      - type: bind
        source: ./grafana/dashboards.yaml
        target: /etc/grafana/provisioning/dashboards/dashboard.yaml
        read_only: false
      - type: bind
        source: ./grafana/dashboards
        target: /var/lib/grafana/dashboards
        read_only: false
      - type: volume
        source: monitoring-grafana-data
        target: /var/lib/grafana
        read_only: false

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
    external: false
    internal: false
    enable_ipv4: true
    enable_ipv6: false

volumes:
  monitoring-grafana-data:
    name: monitoring-grafana-data
    external: false
  monitoring-prometheus-data:
    name: monitoring-prometheus-data
    external: false
  monitoring-loki-data:
    name: monitoring-loki-data
    external: false
