---
name: monitoring

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:-latest}
    container_name: monitoring-cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg
    hostname: monitoring-cadvisor
    networks:
      monitoring-network: null
    ports:
      - name: web (http)
        target: 8080
        published: ${CADVISOR_HTTP_PORT:-8080}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /dev/disk
        target: /dev/disk
        read_only: true
      - type: bind
        source: /etc/machine-id
        target: /etc/machine-id
        read_only: true

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: monitoring-prometheus
    restart: unless-stopped
    hostname: monitoring-prometheus
    networks:
      monitoring-network: null
    ports:
      - name: web (http)
        target: 9090
        published: ${PROMETHEUS_HTTP_PORT:-9090}
        host_ip: 0.0.0.0
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - type: bind
        source: ./prometheus.yaml
        target: /etc/prometheus/prometheus.yml
        read_only: false

networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge
    external: false
    internal: false
    enable_ipv4: true
    enable_ipv6: false
